// ISO-3166-1 alpha-2 country list. Used by the GlobePicker fallback
// selector and the Stage 1 continent counter.
export interface Country {
  code: string   // ISO-3166-1 alpha-2
  name: string
  continent: string
}

export const COUNTRIES: Country[] = [
  { code: "AD", name: "Andorra", continent: "Europe" },
  { code: "AE", name: "United Arab Emirates", continent: "Asia" },
  { code: "AF", name: "Afghanistan", continent: "Asia" },
  { code: "AG", name: "Antigua and Barbuda", continent: "North America" },
  { code: "AL", name: "Albania", continent: "Europe" },
  { code: "AM", name: "Armenia", continent: "Asia" },
  { code: "AO", name: "Angola", continent: "Africa" },
  { code: "AR", name: "Argentina", continent: "South America" },
  { code: "AT", name: "Austria", continent: "Europe" },
  { code: "AU", name: "Australia", continent: "Oceania" },
  { code: "AZ", name: "Azerbaijan", continent: "Asia" },
  { code: "BA", name: "Bosnia and Herzegovina", continent: "Europe" },
  { code: "BB", name: "Barbados", continent: "North America" },
  { code: "BD", name: "Bangladesh", continent: "Asia" },
  { code: "BE", name: "Belgium", continent: "Europe" },
  { code: "BF", name: "Burkina Faso", continent: "Africa" },
  { code: "BG", name: "Bulgaria", continent: "Europe" },
  { code: "BH", name: "Bahrain", continent: "Asia" },
  { code: "BI", name: "Burundi", continent: "Africa" },
  { code: "BJ", name: "Benin", continent: "Africa" },
  { code: "BN", name: "Brunei", continent: "Asia" },
  { code: "BO", name: "Bolivia", continent: "South America" },
  { code: "BR", name: "Brazil", continent: "South America" },
  { code: "BS", name: "Bahamas", continent: "North America" },
  { code: "BT", name: "Bhutan", continent: "Asia" },
  { code: "BW", name: "Botswana", continent: "Africa" },
  { code: "BY", name: "Belarus", continent: "Europe" },
  { code: "BZ", name: "Belize", continent: "North America" },
  { code: "CA", name: "Canada", continent: "North America" },
  { code: "CD", name: "DR Congo", continent: "Africa" },
  { code: "CF", name: "Central African Republic", continent: "Africa" },
  { code: "CG", name: "Congo", continent: "Africa" },
  { code: "CH", name: "Switzerland", continent: "Europe" },
  { code: "CI", name: "Côte d'Ivoire", continent: "Africa" },
  { code: "CL", name: "Chile", continent: "South America" },
  { code: "CM", name: "Cameroon", continent: "Africa" },
  { code: "CN", name: "China", continent: "Asia" },
  { code: "CO", name: "Colombia", continent: "South America" },
  { code: "CR", name: "Costa Rica", continent: "North America" },
  { code: "CU", name: "Cuba", continent: "North America" },
  { code: "CV", name: "Cabo Verde", continent: "Africa" },
  { code: "CY", name: "Cyprus", continent: "Europe" },
  { code: "CZ", name: "Czechia", continent: "Europe" },
  { code: "DE", name: "Germany", continent: "Europe" },
  { code: "DJ", name: "Djibouti", continent: "Africa" },
  { code: "DK", name: "Denmark", continent: "Europe" },
  { code: "DM", name: "Dominica", continent: "North America" },
  { code: "DO", name: "Dominican Republic", continent: "North America" },
  { code: "DZ", name: "Algeria", continent: "Africa" },
  { code: "EC", name: "Ecuador", continent: "South America" },
  { code: "EE", name: "Estonia", continent: "Europe" },
  { code: "EG", name: "Egypt", continent: "Africa" },
  { code: "ER", name: "Eritrea", continent: "Africa" },
  { code: "ES", name: "Spain", continent: "Europe" },
  { code: "ET", name: "Ethiopia", continent: "Africa" },
  { code: "FI", name: "Finland", continent: "Europe" },
  { code: "FJ", name: "Fiji", continent: "Oceania" },
  { code: "FM", name: "Micronesia", continent: "Oceania" },
  { code: "FR", name: "France", continent: "Europe" },
  { code: "GA", name: "Gabon", continent: "Africa" },
  { code: "GB", name: "United Kingdom", continent: "Europe" },
  { code: "GD", name: "Grenada", continent: "North America" },
  { code: "GE", name: "Georgia", continent: "Asia" },
  { code: "GH", name: "Ghana", continent: "Africa" },
  { code: "GM", name: "Gambia", continent: "Africa" },
  { code: "GN", name: "Guinea", continent: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", continent: "Africa" },
  { code: "GR", name: "Greece", continent: "Europe" },
  { code: "GT", name: "Guatemala", continent: "North America" },
  { code: "GW", name: "Guinea-Bissau", continent: "Africa" },
  { code: "GY", name: "Guyana", continent: "South America" },
  { code: "HN", name: "Honduras", continent: "North America" },
  { code: "HR", name: "Croatia", continent: "Europe" },
  { code: "HT", name: "Haiti", continent: "North America" },
  { code: "HU", name: "Hungary", continent: "Europe" },
  { code: "ID", name: "Indonesia", continent: "Asia" },
  { code: "IE", name: "Ireland", continent: "Europe" },
  { code: "IL", name: "Israel", continent: "Asia" },
  { code: "IN", name: "India", continent: "Asia" },
  { code: "IQ", name: "Iraq", continent: "Asia" },
  { code: "IR", name: "Iran", continent: "Asia" },
  { code: "IS", name: "Iceland", continent: "Europe" },
  { code: "IT", name: "Italy", continent: "Europe" },
  { code: "JM", name: "Jamaica", continent: "North America" },
  { code: "JO", name: "Jordan", continent: "Asia" },
  { code: "JP", name: "Japan", continent: "Asia" },
  { code: "KE", name: "Kenya", continent: "Africa" },
  { code: "KG", name: "Kyrgyzstan", continent: "Asia" },
  { code: "KH", name: "Cambodia", continent: "Asia" },
  { code: "KI", name: "Kiribati", continent: "Oceania" },
  { code: "KM", name: "Comoros", continent: "Africa" },
  { code: "KN", name: "Saint Kitts and Nevis", continent: "North America" },
  { code: "KP", name: "North Korea", continent: "Asia" },
  { code: "KR", name: "South Korea", continent: "Asia" },
  { code: "KW", name: "Kuwait", continent: "Asia" },
  { code: "KZ", name: "Kazakhstan", continent: "Asia" },
  { code: "LA", name: "Laos", continent: "Asia" },
  { code: "LB", name: "Lebanon", continent: "Asia" },
  { code: "LC", name: "Saint Lucia", continent: "North America" },
  { code: "LI", name: "Liechtenstein", continent: "Europe" },
  { code: "LK", name: "Sri Lanka", continent: "Asia" },
  { code: "LR", name: "Liberia", continent: "Africa" },
  { code: "LS", name: "Lesotho", continent: "Africa" },
  { code: "LT", name: "Lithuania", continent: "Europe" },
  { code: "LU", name: "Luxembourg", continent: "Europe" },
  { code: "LV", name: "Latvia", continent: "Europe" },
  { code: "LY", name: "Libya", continent: "Africa" },
  { code: "MA", name: "Morocco", continent: "Africa" },
  { code: "MC", name: "Monaco", continent: "Europe" },
  { code: "MD", name: "Moldova", continent: "Europe" },
  { code: "ME", name: "Montenegro", continent: "Europe" },
  { code: "MG", name: "Madagascar", continent: "Africa" },
  { code: "MH", name: "Marshall Islands", continent: "Oceania" },
  { code: "MK", name: "North Macedonia", continent: "Europe" },
  { code: "ML", name: "Mali", continent: "Africa" },
  { code: "MM", name: "Myanmar", continent: "Asia" },
  { code: "MN", name: "Mongolia", continent: "Asia" },
  { code: "MR", name: "Mauritania", continent: "Africa" },
  { code: "MT", name: "Malta", continent: "Europe" },
  { code: "MU", name: "Mauritius", continent: "Africa" },
  { code: "MV", name: "Maldives", continent: "Asia" },
  { code: "MW", name: "Malawi", continent: "Africa" },
  { code: "MX", name: "Mexico", continent: "North America" },
  { code: "MY", name: "Malaysia", continent: "Asia" },
  { code: "MZ", name: "Mozambique", continent: "Africa" },
  { code: "NA", name: "Namibia", continent: "Africa" },
  { code: "NE", name: "Niger", continent: "Africa" },
  { code: "NG", name: "Nigeria", continent: "Africa" },
  { code: "NI", name: "Nicaragua", continent: "North America" },
  { code: "NL", name: "Netherlands", continent: "Europe" },
  { code: "NO", name: "Norway", continent: "Europe" },
  { code: "NP", name: "Nepal", continent: "Asia" },
  { code: "NR", name: "Nauru", continent: "Oceania" },
  { code: "NZ", name: "New Zealand", continent: "Oceania" },
  { code: "OM", name: "Oman", continent: "Asia" },
  { code: "PA", name: "Panama", continent: "North America" },
  { code: "PE", name: "Peru", continent: "South America" },
  { code: "PG", name: "Papua New Guinea", continent: "Oceania" },
  { code: "PH", name: "Philippines", continent: "Asia" },
  { code: "PK", name: "Pakistan", continent: "Asia" },
  { code: "PL", name: "Poland", continent: "Europe" },
  { code: "PT", name: "Portugal", continent: "Europe" },
  { code: "PW", name: "Palau", continent: "Oceania" },
  { code: "PY", name: "Paraguay", continent: "South America" },
  { code: "QA", name: "Qatar", continent: "Asia" },
  { code: "RO", name: "Romania", continent: "Europe" },
  { code: "RS", name: "Serbia", continent: "Europe" },
  { code: "RU", name: "Russia", continent: "Europe" },
  { code: "RW", name: "Rwanda", continent: "Africa" },
  { code: "SA", name: "Saudi Arabia", continent: "Asia" },
  { code: "SB", name: "Solomon Islands", continent: "Oceania" },
  { code: "SC", name: "Seychelles", continent: "Africa" },
  { code: "SD", name: "Sudan", continent: "Africa" },
  { code: "SE", name: "Sweden", continent: "Europe" },
  { code: "SG", name: "Singapore", continent: "Asia" },
  { code: "SI", name: "Slovenia", continent: "Europe" },
  { code: "SK", name: "Slovakia", continent: "Europe" },
  { code: "SL", name: "Sierra Leone", continent: "Africa" },
  { code: "SM", name: "San Marino", continent: "Europe" },
  { code: "SN", name: "Senegal", continent: "Africa" },
  { code: "SO", name: "Somalia", continent: "Africa" },
  { code: "SR", name: "Suriname", continent: "South America" },
  { code: "SS", name: "South Sudan", continent: "Africa" },
  { code: "ST", name: "São Tomé and Príncipe", continent: "Africa" },
  { code: "SV", name: "El Salvador", continent: "North America" },
  { code: "SY", name: "Syria", continent: "Asia" },
  { code: "SZ", name: "Eswatini", continent: "Africa" },
  { code: "TD", name: "Chad", continent: "Africa" },
  { code: "TG", name: "Togo", continent: "Africa" },
  { code: "TH", name: "Thailand", continent: "Asia" },
  { code: "TJ", name: "Tajikistan", continent: "Asia" },
  { code: "TL", name: "Timor-Leste", continent: "Asia" },
  { code: "TM", name: "Turkmenistan", continent: "Asia" },
  { code: "TN", name: "Tunisia", continent: "Africa" },
  { code: "TO", name: "Tonga", continent: "Oceania" },
  { code: "TR", name: "Turkey", continent: "Asia" },
  { code: "TT", name: "Trinidad and Tobago", continent: "North America" },
  { code: "TV", name: "Tuvalu", continent: "Oceania" },
  { code: "TW", name: "Taiwan", continent: "Asia" },
  { code: "TZ", name: "Tanzania", continent: "Africa" },
  { code: "UA", name: "Ukraine", continent: "Europe" },
  { code: "UG", name: "Uganda", continent: "Africa" },
  { code: "US", name: "United States", continent: "North America" },
  { code: "UY", name: "Uruguay", continent: "South America" },
  { code: "UZ", name: "Uzbekistan", continent: "Asia" },
  { code: "VC", name: "Saint Vincent and the Grenadines", continent: "North America" },
  { code: "VE", name: "Venezuela", continent: "South America" },
  { code: "VN", name: "Vietnam", continent: "Asia" },
  { code: "VU", name: "Vanuatu", continent: "Oceania" },
  { code: "WS", name: "Samoa", continent: "Oceania" },
  { code: "YE", name: "Yemen", continent: "Asia" },
  { code: "ZA", name: "South Africa", continent: "Africa" },
  { code: "ZM", name: "Zambia", continent: "Africa" },
  { code: "ZW", name: "Zimbabwe", continent: "Africa" },
]

const BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]))

// How many distinct continents the given country codes span.
export function continentCount(codes: string[]): number {
  const set = new Set<string>()
  for (const code of codes) {
    const country = BY_CODE.get(code)
    if (country) set.add(country.continent)
  }
  return set.size
}
