import { Resend } from "resend"
import type { Itinerary } from "./types"

const resend = new Resend(process.env.RESEND_API_KEY)

function buildHtml(itinerary: Itinerary): string {
  const daysHtml = itinerary.days
    .map((day) => {
      const itemsHtml = day.items
        .map(
          (item) => `
        <tr>
          <td style="padding:10px 0;border-bottom:1px solid #e5e0d8;">
            <strong style="display:block;font-size:15px;color:#2a2218;">${item.name}</strong>
            ${item.cityName ? `<span style="font-size:11px;color:#8a7e6e;text-transform:capitalize;">${item.cityName}</span>` : ""}
            ${item.shortDescription ? `<p style="margin:4px 0 0;font-size:13px;color:#8a7e6e;line-height:1.4;">${item.shortDescription}</p>` : ""}
          </td>
        </tr>`,
        )
        .join("")
      return `
      <h2 style="font-family:Georgia,serif;font-size:18px;font-weight:400;margin:28px 0 8px;color:#2a2218;">
        Day ${day.dayIndex + 1}
      </h2>
      <table style="width:100%;border-collapse:collapse;">${itemsHtml}</table>`
    })
    .join("")

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:32px 24px;color:#2a2218;background:#faf7f2;">
  <h1 style="font-size:28px;font-weight:400;margin-bottom:4px;line-height:1.1;">${itinerary.title}</h1>
  <p style="font-size:13px;color:#8a7e6e;margin-top:4px;">Your Ohana itinerary</p>
  ${daysHtml}
  <hr style="border:none;border-top:1px solid #e5e0d8;margin:32px 0;">
  <p style="font-size:11px;color:#8a7e6e;">
    Generated by <a href="https://ohana.travel" style="color:#8a7e6e;">Ohana</a>
  </p>
</body>
</html>`
}

export async function sendItineraryEmail(to: string, itinerary: Itinerary): Promise<void> {
  await resend.emails.send({
    from: "Ohana <hello@ohana.travel>",
    to,
    subject: itinerary.title,
    html: buildHtml(itinerary),
  })
}
