import nodemailer from "nodemailer"
import type { Itinerary } from "./types"

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

function buildHtml(itinerary: Itinerary): string {
  const daysHtml = itinerary.days
    .map((day) => {
      const itemsHtml = day.items
        .map(
          (item) => `
        <tr>
          <td style="padding:10px 0;border-bottom:1px solid #e5e0d8;">
            <strong style="display:block;font-size:15px;color:#2a2218;">${escapeHtml(item.name)}</strong>
            ${item.cityName ? `<span style="font-size:11px;color:#8a7e6e;text-transform:capitalize;">${escapeHtml(item.cityName)}</span>` : ""}
            ${item.shortDescription ? `<p style="margin:4px 0 0;font-size:13px;color:#8a7e6e;line-height:1.4;">${escapeHtml(item.shortDescription)}</p>` : ""}
          </td>
        </tr>`,
        )
        .join("")
      return `
      <h2 style="font-family:Georgia,serif;font-size:18px;font-weight:400;margin:28px 0 8px;color:#2a2218;">
        Day ${day.dayIndex + 1}
      </h2>
      <table style="width:100%;border-collapse:collapse;">${itemsHtml}</table>`
    })
    .join("")

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Georgia,serif;max-width:600px;margin:0 auto;padding:32px 24px;color:#2a2218;background:#faf7f2;">
  <h1 style="font-size:28px;font-weight:400;margin-bottom:4px;line-height:1.1;">${escapeHtml(itinerary.title)}</h1>
  <p style="font-size:13px;color:#8a7e6e;margin-top:4px;">Your Ohana itinerary</p>
  ${daysHtml}
  <hr style="border:none;border-top:1px solid #e5e0d8;margin:32px 0;">
  <p style="font-size:11px;color:#8a7e6e;">
    Generated by <a href="https://ohana.travel" style="color:#8a7e6e;">Ohana</a>
  </p>
</body>
</html>`
}

export async function sendItineraryEmail(to: string, itinerary: Itinerary): Promise<void> {
  const { BREVO_SMTP_HOST, BREVO_SMTP_PORT, BREVO_SMTP_USER, BREVO_SMTP_PASS } = process.env

  if (!BREVO_SMTP_HOST || !BREVO_SMTP_USER || !BREVO_SMTP_PASS) {
    console.log("[email] SMTP credentials not set — skipping send")
    return
  }

  const transport = nodemailer.createTransport({
    host: BREVO_SMTP_HOST,
    port: BREVO_SMTP_PORT ? parseInt(BREVO_SMTP_PORT, 10) : 587,
    secure: false,
    requireTLS: true,
    auth: {
      user: BREVO_SMTP_USER,
      pass: BREVO_SMTP_PASS,
    },
  })

  await transport.sendMail({
    from: '"Ohana" <hello@ohana.travel>',
    to,
    subject: itinerary.title,
    html: buildHtml(itinerary),
  })
}
